version: '2'
services:
  sql-enc:
    image: mariadb:10.5
    container_name: ${appname}-sql-enc
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql-root-pass}
      MYSQL_DATABASE: youPHPtube-encoder
      MYSQL_USER: youPHPtube
      MYSQL_PASSWORD: ${mysql-pass}
    volumes:
      - ./data/sql-enc:/var/lib/sql/
    restart: always

  phpmyadmin:
    container_name: ${appname}-sqladmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: sql-enc, sql-app
    ports:
      - "8080:80"
    restart: always
  
  encoder:
    image: leejoneshane/youphptube-encoder
    
    environment:
      DOMAIN: fqdn_of_the_server
      DOMAIN_PROTOCOL: http
      ADMIN_PASSWORD: your_password
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: your_db_password
    ports:
      - "8000:80"
    restart: always

  youphptube:
    image: leejoneshane/youphptube
    environment:
      SITE_TITLE: I_love_videos
      DOMAIN: fqdn_of_the_server
      DOMAIN_PROTOCOL: http
      ADMIN_EMAIL: your_email
      ADMIN_PASSWORD: your_password
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: your_db_password
      LANG: en
      ENCODER: http://fqdn_of_the_server:8000
    ports:
      - "80:80"
    restart: always
