version: '2'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: your_db_password
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    restart: always
  
  youphptube:
    image: leejoneshane/youphptube
    environment:
      SITE_TITLE: I_love_videos
      DOMAIN: fqdn_of_the_server
      DOMAIN_PROTOCOL: http
      ADMIN_EMAIL: your_email
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: your_db_password
      LANG: tw
    ports:
      - "80:80"
      - "443:443"
    restart: always
